# Generated by Django 2.2.16 on 2021-11-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20211122_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка1', 'verbose_name_plural': 'Подписки'},
        ),
    ]
