# Generated by Django 2.2.19 on 2022-01-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0022_auto_20211129_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post', verbose_name='Оценённый пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_like', to=settings.AUTH_USER_MODEL, verbose_name='Поставил лайк')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.AddConstraint(
            model_name='userpostlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='user_post_like_unique'),
        ),
    ]
