# Generated by Django 2.2.19 on 2022-01-25 09:25

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20220125_1221'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userpostlike',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('post')), name='user_is_not_author'),
        ),
    ]
