# Generated by Django 2.2.19 on 2022-01-25 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0024_auto_20220125_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPostLike',
            new_name='Like',
        ),
    ]
