# Generated by Django 2.2.19 on 2022-01-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20220125_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='user_is_not_author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
